    name: Migrate via Pipeline
    on:
      push:
        branches:
          - main
    jobs:
      Deploy-Asset:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Get changed files
            id: changed-files
            uses: tj-actions/changed-files@v12
            with:
              separator: ","
              quotepath: false
          - name: Power BI Pipeline Deploy
            uses: nathangiusti/Power-BI-Pipeline-Deploy@v2.5
            with:
              files: ${{ steps.changed-files.outputs.all_modified_files }}
              separator: ","
              tenant_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              config_file: ".github/config/pipeline-deploy-config.yaml"
            env:
              CLIENT_ID: ${{ secrets.CLIENT_ID }}
              CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
